### ISSUE TITLE
Might want to look at isEqualNode and isSameNode for a possible performance bump 

### ISSUE THREAD

**Issue by kristoferjoseph** [bigskysoftware/idiomorph#1]
Stoked to see someone else working on this problem 🙌
https://developer.mozilla.org/en-US/docs/Web/API/Node/isEqualNode
https://developer.mozilla.org/en-US/docs/Web/API/Node/isSameNode

**Comment by 1cg** [comment]
as of right now, perf seems acceptable: within 20% of morphdom in large cases, faster in smaller cases, but I'll keep it in mind, thank you!
