### ISSUE TITLE
Bug Report: `hx-swap` "morph:outerHTML" Doesn't Recognize New `hx-trigger` Attributes

### ISSUE THREAD

**Issue by HenryMorgan-cd2** [bigskysoftware/idiomorph#14]
#### Description:
When using the `idiomorph-ext` extension with `htmx`, setting `hx-swap` to "morph:outerHTML" doesn't properly recognize and apply new `hx-trigger` attributes from the fetched content.

#### Reproduction:

LIVE EXAMPLE: https://clever-clam-66.deno.dev/
GITHUB: https://github.com/HenryMorgan-cd2/htmx-idiomorph-swap-bug

```html
<!-- /content -->
<div
  hx-get="/content"
  hx-swap="outerHTML"
  hx-trigger="load delay:1s"
>
  DATE: ${new Date()}
</div>
```

2. HTML Markup (showcasing the issue):
```html
<div hx-ext="morph">
  <div
    hx-get="/content"
    hx-swap="morph:outerHTML"
    hx-trigger="load 1s"
  >
    ORIGINAL CONTENT
  </div>
</div>
```

#### Expected Behavior:
On swapping, the newly fetched content's `hx-trigger` attribute should be respected and its behavior should be applied.
Causing this component to load poll.

#### Actual Behavior:
The hx-trigger is not applied to the newly fetched content so the content does not poll.

#### Additional Information:
If the original element has a hx-trigger of "every 1s", then that trigger will still be active post-swap.

**Comment by 1cg** [comment]
This should be fixed in the latest version of idiomorph (v0.2.0)
