### ISSUE TITLE
Template contents are not replaced on merge

### ISSUE THREAD

**Issue by caleb** [bigskysoftware/idiomorph#15]
I'm trying to merge two nodes that contain a `<template>` and after the merge the template contains the contents from the old node.

Does it make sense to just replace template node's contents with the new version?

Here's a sandbox showing the issue:

https://codesandbox.io/s/immutable-tdd-mk7mtk?file=/src/index.mjs

Click the button and then use dev tools to inspect the DOM of the result panel.

**Comment by caleb** [comment]
For anybody who runs into this, I am using this callback and it seems to fix the problem for me:

```js
Idiomorph.morph(e, this.templateContent, {
    callbacks: {
      afterNodeMorphed: (oldEl, newEl) => {
        if (oldEl instanceof HTMLTemplateElement && newEl instanceof HTMLTemplateElement) {
          oldEl.content.replaceChildren(...newEl.content.children);
        }
      }
    }
})
```

**Comment by 1cg** [comment]
hey caleb, would you mind contributing a test for this so I can see what you think should work?

**Comment by caleb** [comment]
Sure thing, let me come up with a test.

**Comment by davegaeddert** [comment]
I'm running into a similar questions with `<template>` tags on the page. Unfortunately I'm having trouble getting the tests to run... I think this is a really basic test for it? I'll keep trying but @1cg if you know of any tricks to running the tests, let me know!

```js
it('can morph a template tag properly', function()
{
    let initial = parseHTML("<div><template>Foo</template></div>");
    let finalSrc = '<div><template>Bar</template></div>';
    let final = parseHTML(finalSrc);
    Idiomorph.morph(initial.content, final.content);
    initial.content.outerHTML.should.equal(finalSrc);
});
```

**Comment by seanpdoyle** [comment]
I've opened https://github.com/bigskysoftware/idiomorph/pull/49 to try and resolve this issue.
