### ISSUE TITLE
htmx - possible to preserve input value?

### ISSUE THREAD

**Issue by bartoszkrawczyk2** [bigskysoftware/idiomorph#29]
Hi, is there any way to preserve input value after swap?

**Comment by bartoszkrawczyk2** [comment]
It can be achieved with: `hx-swap="morph:{ignoreActiveValue:true}"`.

Can be closed now.

**Comment by cj** [comment]
@bartoszkrawczyk2 I tried this with hx-swap-oob but it tries to use {ignoreActiveValue:true} as part of the selector. 

```
htmx__org.js?v=9dcca19b:533 Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': '{ignoreActiveValue:true}' is not a valid selector.
```

**Comment by C0DK** [comment]
So the answer is 'no'?
