### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by cmer** [bigskysoftware/idiomorph#41]
I am running into an exception. Not sure what the root cause is. Here's the stack trace and a screenshot of where it crashes. Let me know what else you need to solve this!

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'name')
    at syncNodeFrom (idiomorph.esm.js:294:53)
    at morphOldNodeTo (idiomorph.esm.js:147:21)
    at morphNormalizedContent (idiomorph.esm.js:91:35)
    at Object.morph (idiomorph.esm.js:53:20)
    at event.detail.render [as renderElement] (application.js:24:15)
    at FrameRenderer.loadFrameElement (turbo.es2017-esm.js:1900:10)
    at turbo.es2017-esm.js:1889:12
    at Bardo.preservingPermanentElements (turbo.es2017-esm.js:1721:11)
    at FrameRenderer.preservingPermanentElements (turbo.es2017-esm.js:1814:17)
    at FrameRenderer.render (turbo.es2017-esm.js:1888:10)
syncNodeFrom @ idiomorph.esm.js:294
morphOldNodeTo @ idiomorph.esm.js:147
morphNormalizedContent @ idiomorph.esm.js:91
morph @ idiomorph.esm.js:53
event.detail.render @ application.js:24
loadFrameElement @ turbo.es2017-esm.js:1900
(anonymous) @ turbo.es2017-esm.js:1889
preservingPermanentElements @ turbo.es2017-esm.js:1721
preservingPermanentElements @ turbo.es2017-esm.js:1814
render @ turbo.es2017-esm.js:1888
await in render (async)
render @ turbo.es2017-esm.js:1888
await in render (async)
renderSnapshot @ turbo.es2017-esm.js:1529
render @ turbo.es2017-esm.js:1489
await in render (async)
loadFrameResponse_fn @ turbo.es2017-esm.js:6001
await in loadFrameResponse_fn (async)
loadResponse @ turbo.es2017-esm.js:5824
await in loadResponse (async)
formSubmissionSucceededWithResponse @ turbo.es2017-esm.js:5926
requestSucceededWithResponse @ turbo.es2017-esm.js:1169
receive @ turbo.es2017-esm.js:848
perform @ turbo.es2017-esm.js:825
await in perform (async)
start @ turbo.es2017-esm.js:1109
formSubmitted @ turbo.es2017-esm.js:5876
(anonymous) @ turbo.es2017-esm.js:1390
```
![CleanShot 2024-02-27 at 16 38 40@2x](https://github.com/bigskysoftware/idiomorph/assets/412/aeeb4096-604a-4eb2-a5e4-3a7d5f7242a1)

![CleanShot 2024-02-27 at 16 42 15@2x](https://github.com/bigskysoftware/idiomorph/assets/412/b3255d88-1208-4969-88fb-9faf5cd00c3b)

**Comment by cmer** [comment]
Adding another bogus attribute (eg `foo="bar"`) to my `turbo-frame` solves the issue. It doesn't like the fact that there's only 1 attribute.

**Comment by jameskerr** [comment]
Interesting! Thank you! @cmer  for the fix.

**Comment by jameskerr** [comment]
I'm running into this as well in the same way.

**Comment by matchu** [comment]
For my Turbo Frames, I'm working around this by:

```js
Idiomorph.morph(currentElement, newElement.innerHTML, {
	morphStyle: "innerHTML",
});
```

**Comment by 1cg** [comment]
Hey all, we have a turbo user, @botandrose, who is working with me to smooth over the rough edges.  I hope to have an improved release out soon and an even better release out in the medium-term.

**Comment by botandrose** [comment]
Hi @cmer, thank you for the screenshots! I'm going to try to reduce this down to a failing test case, and the screenshots are invaluable.

**Comment by botandrose** [comment]
@cmer @jameskerr @matchu I'm having a hard time reproducing this in the lab. Are any of you able to reproduce this now at will, perhaps by removing your various workarounds? I have a hypothesis about what's going on (NamedNodeMap has footguns), but I really want to be able to nail it down in a test.

**Comment by botandrose** [comment]
Expanding on the previous comment, my hypothesis is that this issue is ultimately due to `Element#attributes` returning a `NamedNodeMap`, which is _live_, i.e. any changes to the DOM are immediately reflected within the NamedNodeMap instance, which can mess with iteration. It seems that Carson has attempted to work around this by iterating backwards through the NamedNodeMap, but I suspect that that isn't enough to avoid unexpected behavior.

From https://www.oreilly.com/library/view/javascript-the-definitive/0596000480/re534.html (emphasis mine)
> Although the NamedNodeMap interface allows you to iterate through its nodes by position, it does not represent an ordered collection of nodes. Any changes made to the NamedNodeMap (such as by removeNamedItem( ) or setNamedItem( )) may result in a complete reordering of the elements. **Thus, you must not modify a NamedNodeMap while you are iterating through its elements.**

So I think we just need to create our own non-live map of attributes within `syncNodeFrom`. I have this ready to go in a branch, but I really want to see the failure happen, capture it in a test, and then verify that this approach does indeed fix it.

Can any of you help me with this?

**Comment by botandrose** [comment]
Without reproduction, the only thing I can think of that would cause this is either the `busy` or `complete` attributes are toggled off  mid-iteration by Turbo's own request cycle, thus resulting in this error. While I would greatly prefer to have confirmation of this hypothesis, and a test in place to prevent regression, it seems clear that we shouldn't be iterating on a live map, in principle. So I'm going to push a PR that marks this as addressed, and if the issue persists, someone can reopen.
