### ISSUE TITLE
Please publish new version with the module entry in package.json

### ISSUE THREAD

**Issue by kristoferjoseph** [bigskysoftware/idiomorph#51]
The currently published version 0.3.0 omits the module entry in package.json that was added recently.
Thank you kindly.

**Comment by eloyesp** [comment]
Also, it would be nice to export `Idiomorph` instead of `{Idiomorph}`.

That is: https://github.com/bigskysoftware/idiomorph/blob/main/package.json#L25 should read

~~~ json
     "esm" : "(cat src/idiomorph.js && echo \"\nexport Idiomorph;\") > dist/idiomorph.esm.js",
~~~

That way, the ESM usage would be:

~~~ javascript
import {default, morph} from 'idiomorph'
~~~

**Comment by pbowyer** [comment]
```js
export Idiomorph;
```

errors when I test it.

To make this work I had to change the export to:
```js
export const {defaults, morph} = Idiomorph;
```
