### ISSUE TITLE
Myriad issues porting to Typescript, shows JSDoc currently are invalid

### ISSUE THREAD

**Issue by delaneyj** [bigskysoftware/idiomorph#64]
Datastar has a port of idiomorph that's over 6 months old.  Since then idiomorph has added JSDocs.  However using those to port to TS has shown issues with the current types...

https://gist.github.com/delaneyj/18f4e3e090da15590a0f2862a6314b66

Happy to work through these just need some guidance to intent.  Silence the errors is different from know they can not happen

**Comment by 1cg** [comment]
should be fixed in `main` and in next release (later this week?)
