### ISSUE TITLE
Request for .0.4.0 release

### ISSUE THREAD

**Issue by scuml** [bigskysoftware/idiomorph#67]
Just got bit by the template morph issue that was patched back in Oct ( #49 ) due to Turbo library fetching the last release and not the latest commit.

Is it time?  A v.0.4.0 tag would be the ideal Christmas gift for many family members this year.

**Comment by 1cg** [comment]
I hope to cut an 0.4 soon!

**Comment by scuml** [comment]
Thank you sir.
